# Generated by Django 5.2.7 on 2025-10-08 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0002_pengaduan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengaduan',
            name='status',
        ),
    ]
