# Generated by Django 5.2.7 on 2025-10-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0003_remove_pengaduan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengaduan',
            name='status',
            field=models.CharField(choices=[('BARU', 'Baru'), ('DIPROSES', 'Diproses'), ('SELESAI', 'Selesai')], default='BARU', max_length=10),
        ),
    ]
